[[main]]
none = "none"

[[main]]
name = "WEB"
pageRef = "web"
identifier = "WYbjdJbdXV"
weight = 9_999

[[main]]
name = "FOR"
pageRef = "for"
identifier = "8eP3ZCcSsg"
weight = 9_999

[[footer]]
none = "none"
